apiVersion: instance.scaleway.jet.crossplane.io/v1alpha1
kind: Server
metadata:
  name: example
spec:
  forProvider:
    type: DEV1-S
    projectId: YOUR_PROJECT_ID
    image: ubuntu_jammy
    zone: fr-par-1
  providerConfigRef:
    name: default
